In [1]:
import autograd.numpy as np
from autograd import grad, jacobian

### Variáveis aleatórias:

$X_1 = \sigma_{esc} \sim \mathcal{N}(40; \; 5^{2}) \; \text{kN}/cm^2$

$X_2 = W \sim \mathcal{N}(50; \; 2,5^{2}) \; cm^3$

$X_3 = M \sim \mathcal{N}(1000; \; 200^{2}) \; \text{kN} \cdot cm^3$

### Equação de Estado Limite

$g(\underline{X}) = X_1 X_2 - X_3$

In [2]:
# Vetor de médias:
M = np.array([40, 50, 1000])

In [3]:
# Vetor desvio padrão:
d = np.array([5, 2.5, 200])

# Matriz desvio padrão:
D = np.diag(d)

print(D)

[[  5.    0.    0. ]
 [  0.    2.5   0. ]
 [  0.    0.  200. ]]


In [4]:
# Vetor gradiente

In [5]:
# Matriz jacobiana

J = np.linalg.inv(D)

print(J)

[[0.2   0.    0.   ]
 [0.    0.4   0.   ]
 [0.    0.    0.005]]


In [19]:
# Equação do estado limite no espaço reduzido Z:  

def g(Z):
    return 12.5*Z[0]*Z[1] + 250*Z[0] + 1000*Z[1] - 200*Z[2] + 1000

In [23]:
# Vetor gradiente no ponto [0,0,0]

ponto_inicial = np.array([0,0,0], dtype=float)

gradiente = grad(g)(ponto_inicial)

print(gradiente)

[ 250. 1000. -200.]


In [47]:
# Função estado limite no ponto = [0,0,0]

g_ponto_inicial = g(ponto_inicial)

g_ponto_inicial

1000.0

In [40]:
# Módulo do vetor gradiente:

np.linalg.norm(gradiente)

1050.0

In [44]:
# Fator de sensibilidade:

alpha = gradiente / 335.41

alpha

array([ 0.74535643,  2.98142572, -0.59628514])

In [45]:
# Índice de confiabilidade:

beta = np.linalg.norm(ponto_inicial)

beta

0.0

In [49]:
z1 = -alpha * (beta + g_ponto_inicial / 335.41)

z1

array([-2.22222483, -8.88889931,  1.77777986])

In [50]:
g(z1)

-8553.097330736184

In [59]:
gradiente = grad(g)(z1)

print(gradiente)

[ 138.88875862  972.22218965 -200.        ]
